version: '3.8'  # Versión de sintaxis de Docker Compose

services:
  db:
    image: postgres:15                 # Usa PostgreSQL 15 (estable)
    restart: always                    # Reinicia si falla
    environment:
      POSTGRES_DB: bd_web_software_odette
      POSTGRES_USER: odette
      POSTGRES_PASSWORD: odette_password
    ports:
      - "5432:5432"                    # Mapea puerto local 5432

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev       # Usamos el Dockerfile.dev para desarrollo
    depends_on:
      - db                            # Espera a que 'db' esté arriba
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bd_web_software_odette
      SPRING_DATASOURCE_USERNAME: odette
      SPRING_DATASOURCE_PASSWORD: odette_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"                   # Exponer la app en localhost:8080
    volumes:
      - .:/app                        # Sincroniza la carpeta local con el contenedor

volumes:
  db_data: {}  # Volumen nombrado para PostgreSQL, si se necesita para persistencia de datos
